import type { Metadata } from "next";

import { NotoSansFont, NotoSerifFont } from "@/lib/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${NotoSansFont.variable} ${NotoSerifFont.variable} antialiased text-base font-normal`}
      >
        {children}
      </body>
    </html>
  );
}
